# Site metadata
keywords: Cryptography, Privacy, Digital Signatures, Security

description: Homepage of Octavio Pérez Kempner
title: Homepage of Octavio Pérez Kempner

author: Octavio Perez-Kempner
authorimg: images/IMG_2509.JPG
authoroccup: Research Engineer

uni: NTT Social Informatics Laboratories
uniurl: https://www.rd.ntt/e/sil/

twitter: octaviopk
bluesky: octaviopk
orcid: 0000-0002-3377-9802
linkedin: octavio-perez-kempner-58990015
dblp: /p/Perez=Kempner:Octavio
scholar: F8zSuhoAAAAJ
keybase: octaviopk

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - articles
  - articlesworeview
  - books
  - theses
  - deli
include:
  - keybase.txt
exclude:
  - Gemfile
  - Gemfile.lock
